### ISSUE TITLE
Any plan on updating it to Vue 2.x compatible?

### ISSUE THREAD

**Issue by phoenixwong** [Bubblings/vue-date-picker#12]
Hi @Bubblings ,

I like your widget and have applied it to some of my Vue 1.x projects. Are you planning on updating it to Vue 2.x compatible? Looking forward to it.

**Comment by reinerBa** [comment]
Pull request #13 
Necessary for compatibility 

- Chang ready to mounted...this.$next() see https://vuejs.org/v2/guide/migration.html#ready-replaced
- The prop is no longer changed and replaced by $data.pickedValue

**Comment by samayo** [comment]
@reinerBa  Does your PR fix #15 ?

**Comment by reinerBa** [comment]
@samayo now it should. But i would recommend you to use a more active plugin like 
https://github.com/charliekassel/vuejs-datepicker
There are so many vue-datepickers that work...

**Comment by 8788** [comment]
#13
