### ISSUE TITLE
Property or method "styleObj" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

### ISSUE THREAD

**Issue by chrisho** [Bubblings/vue-date-picker#15]
cant find styleObj in datepicker.vue

**Comment by matgargano** [comment]
+1

**Comment by vladbash** [comment]
+1

**Comment by ice-2022** [comment]
+1

**Comment by samayo** [comment]
+1 This is the only error I have in my console now, please fix it.

**Comment by sanjayatony** [comment]
+1

**Comment by reinerBa** [comment]
Just add it to the props above of data:

`styleObj: { type: Object, default: {}}`

Then you can insert a prop object or not.

**Comment by Firrero** [comment]
+1

**Comment by 8788** [comment]
Please use the input-style prop in version 2.x
