### ISSUE TITLE
Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"

### ISSUE THREAD

**Issue by rjmrosario** [Bubblings/vue-date-picker#18]
Hi,

I would like to bind the value in the variable, but I receive this error:

Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"

Here's what I did.

datepicker :value.sync='dateSelected' format="MM-DD-YYYY"

I also tried v-model but still same error.

Thanks,
Rizza

**Comment by 8788** [comment]
Fixed in version 2.x
