### ISSUE TITLE
How can disable future date after dropdown calendar

### ISSUE THREAD

**Issue by banha-serhii** [Bubblings/vue-date-picker#22]
How i can disable date from the next day?
![73af12b3-08ee-4031-a3e5-f326a52062f5 png](https://user-images.githubusercontent.com/16404807/52918649-1a8e5f00-3302-11e9-849a-84af33aa5855.jpg)

**Comment by 8788** [comment]
Please use the disabled-date prop in version 2.5.0 or higher.
