### ISSUE TITLE
ParseError: Unexpected token

### ISSUE THREAD

**Issue by sanbeaman** [Bubblings/vue-date-picker#3]
I have imported 'vue-date-picker' in the global vue space, and inside a component. I've ran 'npm update' etc...

but I keep getting this ParseError: UNexpected token

`[12:15:23] gulp-notify: [Laravel Elixir] Browserify Failed!: Unexpected token`

`node_modules/vue-date-picker/src/datepicker.vue:1`
`<style scoped>`
`^`
`ParseError: Unexpected token`

**Comment by Towerful** [comment]
Yup, same problem here.  
I think the work-around would be to grab the source file, drop it in your working directory, and import it as if it was a component you had written. Not ideal.  
It seems using a node module bypasses the vueify step. At least using Laravel Elixir....

**Comment by EHackettTriCore** [comment]
I'm running into a similar issue with Browserify and like @Towerful said you can copy it into it's own vue file in your project for the time being and it works. Obviously this isn't ideal and it would be great if there was a native fix.

**Comment by 8788** [comment]
The latest version has been resolved.
